version: '3.9'
services:
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/code
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - tf-serving
      - db
  tf-serving:
    image: tensorflow/serving:latest
    ports:
      - 8501:8501
    volumes:
      - ./saved_models:/models
    environment:
      - MODEL_CONFIG_FILE=/models/model.config
    command: ["tensorflow_model_server", "--rest_api_port=8501", "--model_config_file=/models/model.config"]
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: