# Generated by Django 3.1.12 on 2024-08-06 14:16

from django.db import migrations, models
import djongo.models.fields
import reviews.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('topics', djongo.models.fields.ArrayField(model_container=reviews.models.Topic)),
            ],
        ),
    ]
